apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: nishadmp/ecommerce-product-service:latest
        ports:
        - name: grpc
          containerPort: 50053
        - name: http
          containerPort: 3003
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_NAME
          value: "saga_product"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: postgres-password
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq:5672"
        - name: JWT_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: jwt-access-secret
