apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
      targetPort: 50053
    - name: http
      protocol: TCP
      port: 3003
      targetPort: 3003
